name: manito
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.2+18

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  auto_size_text:
  cupertino_icons: ^1.0.8
  badges: ^3.1.2
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_dotenv: ^5.2.1
  get: ^4.7.2
  google_mobile_ads: ^6.0.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  photo_manager: ^3.6.4
  photo_manager_image_provider: ^2.2.0
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  supabase_flutter: ^2.8.4
  timeago: ^3.2.2
  flutter_image_compress: ^2.4.0
  path: ^1.9.1
  path_provider: ^2.1.5
  flutter_inappwebview: ^6.1.5
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.6
  flutter_native_splash: ^2.4.6
  introduction_screen: ^3.1.17
  tutorial_coach_mark: ^1.3.0
  easy_localization: ^3.0.7+1
  restart_app: ^1.3.2
  google_sign_in: ^6.2.0
  fluttertoast: ^8.2.12
  flutter_local_notifications: ^19.4.1
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/translations/
    - assets/icons/
    - .env
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Digital
      fonts:
        - asset: assets/fonts/DS-DIGIB.TTF

    - family: CustomIcons
      fonts:
        - asset: assets/fonts/custom_icons.ttf

  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

flutter_native_splash:
  color: "#FFFFFF" # 배경색
  image: assets/images/manito_dog_circle.png # 스플래시 이미지 경로
  android: true
  ios: true
  web: false

  android_12:
    color: "#FFFFFF"
    image: assets/images/manito_dog_circle.png # 스플래시 이미지 경로
